# Generated by Django 5.1.3 on 2024-11-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
